/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket_reservation;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author sinha
 */
public class Seats extends javax.swing.JFrame {

    /**
     * Creates new form Seats
     */
    public static String busNumber = "";
    public static String date = "";
    public static int seatSelected = 0;
    public static int fare = 0;
    
    public Seats(String id, int seatSelected,int fare,String date) {
        this.busNumber = id;
        this.seatSelected = seatSelected;
        this.fare = fare;
        this.date = date;
        initComponents();
        
        jTextField1_seat.setText("please select "+String.valueOf(seatSelected)+" seats");
        //jPanel2 = new seatPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        int a1Flag = 0;
        int a2Flag = 0;
        int a3Flag = 0;
        int b1Flag = 0;
        int b2Flag = 0;
        int b3Flag = 0;
        int c1Flag = 0;
        int c2Flag = 0;
        int c3Flag = 0;
        int d1Flag = 0;
        int d2Flag = 0;
        int d3Flag = 0;
        int e1Flag = 0;
        int e2Flag = 0;
        int e3Flag = 0;
        int f1Flag = 0;
        int f2Flag = 0;
        int f3Flag = 0;
        int g1Flag = 0;
        int g2Flag = 0;
        int g3Flag = 0;
        int h1Flag = 0;
        int h2Flag = 0;
        int h3Flag = 0;
        int i1Flag = 0;
        int i2Flag = 0;
        int i3Flag = 0;
        int i4Flag = 0;
        try {
            FileReader fileReader = new FileReader("seats.txt");
            BufferedReader bufferedReader = new BufferedReader(fileReader);

            String line ;
            while((line = bufferedReader.readLine()) != null) {
                String [] s1 = line.split(",");
                String busid = s1[0];
                if (busNumber.equalsIgnoreCase(busid)) {
                    System.out.println("busNumber "+ busNumber);
                    System.out.println("busid "+ busid);
                    String seatNumber = s1[1];
                    String color = s1[2];
                    System.out.println("color "+ color);
                    if(seatNumber.equalsIgnoreCase("A1")) {
                        if(color.equalsIgnoreCase("RED")){
                            a1Flag = 1;
                            //System.out.println("a1 "+ a1Flag);
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("A2")) {
                        if(color.equalsIgnoreCase("RED")){
                            a2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("A3")) {
                        if(color.equalsIgnoreCase("RED")){
                            a3Flag = 1;
                        }
                    }
                    if(seatNumber.equalsIgnoreCase("B1")) {
                        if(color.equalsIgnoreCase("RED")){
                            b1Flag = 1;
                            //System.out.println("a1 "+ a1Flag);
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("B2")) {
                        if(color.equalsIgnoreCase("RED")){
                            b2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("B3")) {
                        if(color.equalsIgnoreCase("RED")){
                            b3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("C1")) {
                        if(color.equalsIgnoreCase("RED")){
                            c1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("C2")) {
                        if(color.equalsIgnoreCase("RED")){
                            c2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("C3")) {
                        if(color.equalsIgnoreCase("RED")){
                            c3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("D1")) {
                        if(color.equalsIgnoreCase("RED")){
                            d1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("D2")) {
                        if(color.equalsIgnoreCase("RED")){
                            d2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("D3")) {
                        if(color.equalsIgnoreCase("RED")){
                            d3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("E1")) {
                        if(color.equalsIgnoreCase("RED")){
                            e1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("E2")) {
                        if(color.equalsIgnoreCase("RED")){
                            e2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("E3")) {
                        if(color.equalsIgnoreCase("RED")){
                            e3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("F1")) {
                        if(color.equalsIgnoreCase("RED")){
                            f1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("F2")) {
                        if(color.equalsIgnoreCase("RED")){
                            f2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("F3")) {
                        if(color.equalsIgnoreCase("RED")){
                            f3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("G1")) {
                        if(color.equalsIgnoreCase("RED")){
                            g1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("G2")) {
                        if(color.equalsIgnoreCase("RED")){
                            g2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("G3")) {
                        if(color.equalsIgnoreCase("RED")){
                            g3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("H1")) {
                        if(color.equalsIgnoreCase("RED")){
                            h1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("H2")) {
                        if(color.equalsIgnoreCase("RED")){
                            h2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("H3")) {
                        if(color.equalsIgnoreCase("RED")){
                            h3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("I1")) {
                        if(color.equalsIgnoreCase("RED")){
                            i1Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("I2")) {
                        if(color.equalsIgnoreCase("RED")){
                            i2Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("I3")) {
                        if(color.equalsIgnoreCase("RED")){
                            i3Flag = 1;
                        }
                    }
                    else if(seatNumber.equalsIgnoreCase("I4")) {
                        if(color.equalsIgnoreCase("RED")){
                            i3Flag = 1;
                        }
                    }
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex) {
            Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        a1 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        i1 = new javax.swing.JButton();
        i2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        g2 = new javax.swing.JButton();
        h2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        g3 = new javax.swing.JButton();
        h3 = new javax.swing.JButton();
        i4 = new javax.swing.JButton();
        i3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        a2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_seat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ticketing");

        minimize.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        if(a1Flag == 1){
            a1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            a1.setBackground(new java.awt.Color(0, 204, 51));
        }
        a1.setText("A1");
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });

        if(e2Flag == 1){
            e2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            e2.setBackground(new java.awt.Color(0, 204, 51));
        }
        e2.setText("E2");
        e2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e2MouseClicked(evt);
            }
        });

        if(c1Flag == 1){
            c1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            c1.setBackground(new java.awt.Color(0, 204, 51));
        }
        c1.setText("C1");
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });

        if(b1Flag == 1){
            b1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            b1.setBackground(new java.awt.Color(0, 204, 51));
        }
        b1.setText("B1");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });

        if(e1Flag == 1){
            e1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            e1.setBackground(new java.awt.Color(0, 204, 51));
        }
        e1.setText("E1");
        e1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e1MouseClicked(evt);
            }
        });

        if(d1Flag == 1){
            d1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            d1.setBackground(new java.awt.Color(0, 204, 51));
        }
        d1.setText("D1");
        d1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d1MouseClicked(evt);
            }
        });

        if(f1Flag == 1){
            f1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            f1.setBackground(new java.awt.Color(0, 204, 51));
        }
        f1.setText("F1");
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
        });

        if(g1Flag == 1){
            g1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            g1.setBackground(new java.awt.Color(0, 204, 51));
        }
        g1.setText("G1");
        g1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g1MouseClicked(evt);
            }
        });

        if(h1Flag == 1){
            h1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            h1.setBackground(new java.awt.Color(0, 204, 51));
        }
        h1.setText("H1");
        h1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h1MouseClicked(evt);
            }
        });

        if(i1Flag == 1){
            i1.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            i1.setBackground(new java.awt.Color(0, 204, 51));
        }
        i1.setText("I1");
        i1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i1MouseClicked(evt);
            }
        });

        if(i2Flag == 1){
            i2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            i2.setBackground(new java.awt.Color(0, 204, 51));
        }
        i2.setText("I2");
        i2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i2MouseClicked(evt);
            }
        });

        if(b2Flag == 1){
            b2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            b2.setBackground(new java.awt.Color(0, 204, 51));
        }
        b2.setText("B2");
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });

        if(c2Flag == 1){
            c2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            c2.setBackground(new java.awt.Color(0, 204, 51));
        }
        c2.setText("C2");
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });

        if(d2Flag == 1){
            d2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            d2.setBackground(new java.awt.Color(0, 204, 51));
        }
        d2.setText("D2");
        d2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d2MouseClicked(evt);
            }
        });

        if(f2Flag == 1){
            f2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            f2.setBackground(new java.awt.Color(0, 204, 51));
        }
        f2.setText("F2");
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2MouseClicked(evt);
            }
        });

        if(g2Flag == 1){
            g2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            g2.setBackground(new java.awt.Color(0, 204, 51));
        }
        g2.setText("G2");
        g2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g2MouseClicked(evt);
            }
        });
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });

        if(h2Flag == 1){
            h2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            h2.setBackground(new java.awt.Color(0, 204, 51));
        }
        h2.setText("H2");
        h2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h2MouseClicked(evt);
            }
        });

        if(a3Flag == 1){
            a3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            a3.setBackground(new java.awt.Color(0, 204, 51));
        }
        a3.setText("A3");
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });

        if(c3Flag == 1){
            c3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            c3.setBackground(new java.awt.Color(0, 204, 51));
        }
        c3.setText("C3");
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });

        if(b3Flag == 1){
            b3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            b3.setBackground(new java.awt.Color(0, 204, 51));
        }
        b3.setText("B3");
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });

        if(d3Flag == 1){
            d3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            d3.setBackground(new java.awt.Color(0, 204, 51));
        }
        d3.setText("D3");
        d3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                d3MouseClicked(evt);
            }
        });

        if(e3Flag == 1){
            e3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            e3.setBackground(new java.awt.Color(0, 204, 51));
        }
        e3.setText("E3");
        e3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                e3MouseClicked(evt);
            }
        });

        if(f3Flag == 1){
            f3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            f3.setBackground(new java.awt.Color(0, 204, 51));
        }
        f3.setText("F3");
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3MouseClicked(evt);
            }
        });

        if(g3Flag == 1){
            g3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            g3.setBackground(new java.awt.Color(0, 204, 51));
        }
        g3.setText("G3");
        g3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                g3MouseClicked(evt);
            }
        });

        if(h3Flag == 1){
            h3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            h3.setBackground(new java.awt.Color(0, 204, 51));
        }
        h3.setText("H3");
        h3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h3MouseClicked(evt);
            }
        });

        if(i4Flag == 1){
            i4.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            i4.setBackground(new java.awt.Color(0, 204, 51));
        }
        i4.setText("I4");
        i4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i4MouseClicked(evt);
            }
        });

        if(i3Flag == 1){
            i3.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            i3.setBackground(new java.awt.Color(0, 204, 51));
        }
        i3.setText("I3");
        i3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i3MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket_reservation/green.png"))); // NOI18N
        jLabel2.setText("Available");

        if(a2Flag == 1){
            a2.setBackground(new java.awt.Color(255, 0, 0));
        }
        else{
            a2.setBackground(new java.awt.Color(0, 204, 51));
        }
        a2.setText("A2");
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket_reservation/red.png"))); // NOI18N
        jLabel3.setText("Unavailable");

        confirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirm.setText("Confirm");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Seat Plan");

        jTextField1_seat.setEditable(false);
        jTextField1_seat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1_seat.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(h2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(i1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(i2)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(h1)
                            .addComponent(g2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(d2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(i4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(h3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(g3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(d3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b1)
                            .addComponent(c1)
                            .addComponent(d1)
                            .addComponent(e1)
                            .addComponent(f1)
                            .addComponent(g1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(confirm)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1)
                    .addComponent(a2)
                    .addComponent(a3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1)
                    .addComponent(c2)
                    .addComponent(c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1)
                    .addComponent(d2)
                    .addComponent(d3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e1)
                    .addComponent(e2)
                    .addComponent(e3)
                    .addComponent(jTextField1_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1)
                    .addComponent(f2)
                    .addComponent(f3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g1)
                    .addComponent(g2)
                    .addComponent(g3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h1)
                    .addComponent(h2)
                    .addComponent(h3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i1)
                    .addComponent(i2)
                    .addComponent(i4)
                    .addComponent(i3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(confirm)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175)
                .addComponent(minimize)
                .addGap(32, 32, 32)
                .addComponent(close)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minimize)
                            .addComponent(close)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 555, 593);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        
    }//GEN-LAST:event_g2ActionPerformed

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        a1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("A1");
    }//GEN-LAST:event_a1MouseClicked
      
    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        b1.setBackground(new Color(255,0,0).brighter());
         this.reserveTicket("B1");
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        b2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("B2");
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        b3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("B3");
    }//GEN-LAST:event_b3MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        c1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("C1");
    }//GEN-LAST:event_c1MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        c2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("C2");
    }//GEN-LAST:event_c2MouseClicked

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
        c3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("C3");
    }//GEN-LAST:event_c3MouseClicked

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        a2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("A2");
    }//GEN-LAST:event_a2MouseClicked

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
        a3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("A3");
    }//GEN-LAST:event_a3MouseClicked

    private void d1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d1MouseClicked
        d1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("D1"); 
    }//GEN-LAST:event_d1MouseClicked

    private void d2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d2MouseClicked
        d2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("D2");
    }//GEN-LAST:event_d2MouseClicked

    private void d3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_d3MouseClicked
        d3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("D3");
    }//GEN-LAST:event_d3MouseClicked

    private void e1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e1MouseClicked
        e1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("E1");
    }//GEN-LAST:event_e1MouseClicked

    private void e2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e2MouseClicked
        e2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("E2");
    }//GEN-LAST:event_e2MouseClicked

    private void e3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_e3MouseClicked
        e3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("E2");
    }//GEN-LAST:event_e3MouseClicked

    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        f1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("F1");
    }//GEN-LAST:event_f1MouseClicked

    private void f2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseClicked
        f2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("F2");
    }//GEN-LAST:event_f2MouseClicked

    private void f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseClicked
        f3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("F3");
    }//GEN-LAST:event_f3MouseClicked

    private void g1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked
        g1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("G1");
    }//GEN-LAST:event_g1MouseClicked

    private void g2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2MouseClicked
        g2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("G2");
    }//GEN-LAST:event_g2MouseClicked

    private void g3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3MouseClicked
        g3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("G3");
    }//GEN-LAST:event_g3MouseClicked

    private void h1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h1MouseClicked
        h1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("H1");
    }//GEN-LAST:event_h1MouseClicked

    private void h2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h2MouseClicked
        h2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("H2");
    }//GEN-LAST:event_h2MouseClicked

    private void h3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h3MouseClicked
        h3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("H3");
    }//GEN-LAST:event_h3MouseClicked

    private void i1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i1MouseClicked
        i1.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("I1");
    }//GEN-LAST:event_i1MouseClicked

    private void i2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i2MouseClicked
        i2.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("I2");
    }//GEN-LAST:event_i2MouseClicked

    private void i3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i3MouseClicked
        i3.setBackground(new Color(255,0,0).brighter());
        this.reserveTicket("I3");
    }//GEN-LAST:event_i3MouseClicked

    private void i4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i4MouseClicked
       i4.setBackground(new Color(255,0,0).brighter());
       this.reserveTicket("I4");
    }//GEN-LAST:event_i4MouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        int payMoney = seatSelected * fare;
        Pay t = new Pay(payMoney);
        t.setVisible(true);
        t.pack();
        t.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_confirmMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seats(busNumber,seatSelected, fare, date).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JLabel close;
    private javax.swing.JButton confirm;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton g3;
    private javax.swing.JButton h1;
    private javax.swing.JButton h2;
    private javax.swing.JButton h3;
    private javax.swing.JButton i1;
    private javax.swing.JButton i2;
    private javax.swing.JButton i3;
    private javax.swing.JButton i4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1_seat;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables

    private void reserveTicket(String button){
        
        File f1 = new File("reserveTicket.txt");
        File f2 = new File("seats.txt");
        try {
            PrintWriter pw1 = new PrintWriter(new FileOutputStream(f1, true));
            pw1.append( "," + button );
            pw1.close();
            //System.out.println("busnumber " + busNumber);
            
            PrintWriter pw2 = new PrintWriter(new FileOutputStream(f2, true));
            pw2.append(busNumber);
//            pw2.append(",");
//            pw2.append(date);
            pw2.append( "," + button );
            pw2.append( "," + "RED" + System.lineSeparator());
            pw2.close();
            }catch (FileNotFoundException ex) {
                Logger.getLogger(Ticket.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }
}


